# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kanextjsapproutes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: Copy static files
        run: |
         cp -R ./.next/static ./.next/standalone/.next/static
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
         name: node-app
         path: .next/standalone
         include-hidden-files: true


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF1CDC097D3C47C1B2A98B64D20AC83D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF75A3A5CD424E74B672FBB29D867DA4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5D2A2DF0E87A43548D9A7D7951BA5507 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kanextjsapproutes'
          slot-name: 'Production'
          package: .
          
